#+ summary: Find the metatata that contains the given text
#+ method: GET
#+ endpoint_in_url: True

#PREFIX bif: <http://www.openlinksw.com/schemas/bif#>  # for Virtuoso

SELECT ?s ?p ?o
WHERE {
    ?s ?p ?o .
    ?o <bif:contains> ?_text .
}
