#+ summary: Lookup metadata that has the given publisher
#+ method: GET
#+ endpoint_in_url: True

PREFIX dct: <http://purl.org/dc/terms/>
#PREFIX bif: <http://www.openlinksw.com/schemas/bif#> # for Virtuoso

SELECT DISTINCT (?s AS ?ID) (?_publisher_iri AS ?Publisher)
WHERE {
    ?s dct:publisher ?_publisher_iri
}
