#+ summary: Get all themes, only applicable to dataset metadata.
#+ method: GET
#+ endpoint_in_url: True

PREFIX dcat: <http://www.w3.org/ns/dcat#>
#PREFIX bif: <http://www.openlinksw.com/schemas/bif#> # for Virtuoso

SELECT DISTINCT (?o AS ?Theme)
WHERE {
    ?s dcat:theme ?o
}
