#+ summary: Get all licenses, only applicable to distribution metadata.
#+ method: GET
#+ endpoint_in_url: True

PREFIX dct: <http://purl.org/dc/terms/>
#PREFIX bif: <http://www.openlinksw.com/schemas/bif#> # for Virtuoso

SELECT DISTINCT (?o AS ?License)
WHERE {
    ?s dct:license ?o
}
