#+ summary: Get all IDs that are children of the given metadata ID.
#+ method: GET
#+ endpoint_in_url: True

PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX r3d: <http://www.re3data.org/schema/3-0#>
#PREFIX bif: <http://www.openlinksw.com/schemas/bif#>  # for Virtuoso

SELECT (?o AS ?ChildrenID)
WHERE {
    { ?_id_iri r3d:dataCatalog ?o . }
    UNION
    {?_id_iri dcat:dataset ?o .}
    UNION
    {?_id_iri dcat:distribution ?o .}
}
